tap 'homebrew/bundle'

brew 'anyenv'
brew 'direnv'
brew 'gnupg'
brew 'jq'
brew 'pinentry-mac'
brew 'terraform'
brew 'tig'
brew 'tmux'
brew 'tree'

# cask '1password'
cask 'bettertouchtool'
cask 'clipy'
cask 'discord'
cask 'google-chrome'
cask 'docker'
cask 'google-japanese-ime'
cask 'insomnia'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'scroll-reverser'
cask 'skitch'
cask 'slack'
cask 'spotify'
cask 'xbar'
