tap 'homebrew/bundle'

brew 'anyenv'
brew 'direnv'
brew 'git'
brew 'gnupg'
brew 'jq'
brew 'openssl'
brew 'pinentry-mac'
brew 'reattach-to-user-namespace'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'zsh'

# cask '1password'
cask 'bettertouchtool'
cask 'clipy'
cask 'datagrip'
cask 'discord'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'insomnia'
cask 'iterm2'
cask 'rubymine'
cask 'skitch'
cask 'slack'
